### ISSUE TITLE
IPHYRE game not able to run ?

### ISSUE THREAD

**Issue by Lr-2002** [lishiqianhugh/IPHYRE#1]
hello Shiqian, I'm trying to do something on the IPHYRE env. But I'm not able to run the game following the instruction 
```python
from iphyre.simulator import IPHYRE

env = IPHYRE(game='hole')
env.play()

```
Could you help me?

What's more, the snapshot is like this .
![image](https://github.com/lishiqianhugh/IPHYRE/assets/42893558/521272f6-b234-406f-a096-512065f565d9)

PC: Windows11 
env was installed follow your instruction.
Problem:
When i pressed 's' or 'r' or 'n'。Nothing was changed , and it seems the pygame got the pressed key ?
Could you help me?

**Comment by lishiqianhugh** [comment]
Thank you for your attention to I-PHYRE! A higher version of Pygame may cause this error. Pygame==2.1.2 works well!

**Comment by Lr-2002** [comment]
Thanks~ I fixed it under your instruction
